#!/bin/bash

start_server() {
  make server &
  pid=sudo lsof -i:2121 | tail -1 | awk '{print $2}'
  while [ -z "$pid" ]
  do
    pid=`sudo lsof -i:2121 | tail -1 | awk '{print $2}'`
    sleep 1
  done
  echo $pid > pftp.pid
}

stop_server() {
  PID=$(cat pftp.pid)

  sudo kill -SIGINT $PID
  if [ $? -ne 0 ]; then
    echo "process not found"
    exit 1
  fi
  sleep 1
  sudo kill -0 $PID 2>/dev/null
  if [ $? -ne 1 ]; then
    echo "sent signal as SIGTERM"
    sudo kill -SIGTERM $PID
  fi
}

reload_server() {
  PID=$(cat pftp.pid)

  sudo kill -0 $PID 2>/dev/null
  if [ $? -eq 1 ]; then
    echo "process not found"
    exit 1
  else
    echo "sent signal as SIGHUP"
    sudo kill -SIGHUP $PID
  fi
}

case "$1" in
  start)
    start_server
    ;;
  stop)
    stop_server
    ;;
  restart)
    stop_server
    start_server
    ;;
  reload)
    reload_server
    ;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 2
esac
