#!/bin/bash

start_server() {
  make server &
  pid=sudo lsof -i:2121 | tail -1 | awk '{print $2}'
  while [ -z "$pid" ]
  do
    pid=`sudo lsof -i:2121 | tail -1 | awk '{print $2}'`
    sleep 1
  done
  echo $pid > pftp.pid
}

stop_server() {
  PID=$(cat pftp.pid)

  sudo kill -SIGINT $PID
  if [ $? -ne 0 ]; then
    echo "process not found"
    exit 1
  fi
  sleep 1
  sudo kill -0 $PID 2>/dev/null
  if [ $? -ne 1 ]; then
    echo "sent signal as SIGKILL"
    sudo kill -SIGKILL $PID
  fi
}

hup_server() {
  PID=$(cat pftp.pid)
  sudo kill -SIGHUP $PID 2>/dev/null
  [ -x /proc/$PID ]
  if [ $? -ne 1 ]; then
    exit 1
  fi
  exit 0
}
case "$1" in
  start)
    start_server
    ;;
  hup)
    hup_server
    ;;
  stop*)
    stop_server
    ;;
  *)
    echo $"Usage: $0 {start|stop|hup}"
    exit 2
esac
